# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  actions: read
  checks: write

jobs:
  node_ci:
    name: Node CI
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm run test
      - name: Report test results
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: JavaScript test status
          path: 'coverage/clover.xml'
          max-annotations: '40'
          reporter: jest-junit
          fail-on-error: 'false'
      - name: Upload coverage reports to Codecov
        if: success() || failure()
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
